package lib280.tree;

import lib280.base.LinearIterator280;
import lib280.exception.AfterTheEnd280Exception;
import lib280.exception.ContainerEmpty280Exception;
import lib280.exception.NoCurrentItem280Exception;

public class ArrayedBinaryTreeIterator280<I> extends ArrayedBinaryTreePosition280 implements LinearIterator280<I> {

	// This is a reference to the tree that created this iterator object.
	ArrayedBinaryTree280<I> tree;
	
	// An integer that represents the cursor position is inherited from
	// ArrayedBinaryTreePosition280.
	
	/**
	 * Create a new iterator from a given heap.
	 * @param t The heap for which to create a new iterator.
	 */
	public ArrayedBinaryTreeIterator280(ArrayedBinaryTree280<I> t) {
		super(t.currentNode);
		this.tree = t;
	}

	// TODO - Complete the following methods which are required by LinearIterator280<I>
	// Note that these method stubs were automatically generated by IntelliJ and every one of them
	// requires your attention.

	@Override
	public boolean before() {
		return this.currentNode == 0;
	}

	@Override
	public boolean after() {
		return this.currentNode > this.tree.count || this.tree.isEmpty();
	}

	@Override
	public void goForth() throws AfterTheEnd280Exception {
		if(this.after()) throw new AfterTheEnd280Exception("Cannot advance cursor in the after position.");
		this.currentNode++;

	}

	@Override
	public void goFirst() throws ContainerEmpty280Exception {
		if( this.tree.isEmpty() ) throw new ContainerEmpty280Exception("Cannot move to first item of an empty tree.");
		this.currentNode = 1;
	}

	@Override
	public void goBefore() {
		this.currentNode = 0;
	}

	@Override
	public void goAfter() {
		if( this.tree.isEmpty() ) this.currentNode = 0;
		else this.currentNode = this.tree.count + 1;
	}
	public void goBack(){
		if(this.before()) throw new AfterTheEnd280Exception("Cannot advance cursor in the before position.");

		this.currentNode --;
	}

	@Override
	public I item() throws NoCurrentItem280Exception {
		if (this.tree.isEmpty()){throw new NoCurrentItem280Exception("The tree is empty");}

		return this.tree.item();
	}

	@Override
	public boolean itemExists() {

		return this.tree.itemExists();
	}


}
